# Generated by Django 5.1.3 on 2024-11-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('place', models.CharField(max_length=100)),
                ('start_date_tour', models.DateField()),
                ('duration', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('available_places', models.IntegerField()),
                ('occupied_places', models.IntegerField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour_type', models.CharField(choices=[('all_inclusive', 'Все включено'), ('road_and_accommodation', 'Только дорога и проживание')], max_length=50)),
                ('image', models.ImageField(upload_to='static/image/')),
            ],
            options={
                'verbose_name_plural': 'title',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('number_of_people', models.IntegerField(max_length=3)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.tour')),
            ],
            options={
                'verbose_name_plural': 'name',
            },
        ),
    ]
