# Generated by Django 5.1.3 on 2024-11-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_of_people',
            field=models.IntegerField(),
        ),
    ]
