# Generated by Django 5.1.3 on 2024-11-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_alter_user_number_of_people'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name_plural': 'Tour'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
    ]
