# Generated by Django 5.1.3 on 2024-11-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_remove_tour_tour_type_alter_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='place',
            field=models.CharField(max_length=27),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=17),
        ),
    ]
