# Generated by Django 5.1.3 on 2024-11-21 15:38

import web_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_alter_tour_place_alter_tour_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='available_places',
            field=models.IntegerField(help_text='Свободные места'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(help_text='Описание тура (не более 1100 символов)', max_length=1100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(help_text='Длительность тура (в днях)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(help_text='Загрузите квадратное изображение размером не более 1000x1000 пикселей.', upload_to='static/image/img_tour', validators=[web_site.models.validate_square_and_size]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_people',
            field=models.IntegerField(help_text='Максимальное количесвто мест'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='occupied_places',
            field=models.IntegerField(help_text='Занятые места'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='place',
            field=models.CharField(help_text='Локация тура (не более 27 символов)', max_length=27),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, help_text='Цена за одного человека (в формате 0000.00)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date_tour',
            field=models.DateField(help_text='Дата начала тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(help_text='Заголовок тура (не более 17 символов)', max_length=17),
        ),
    ]
