# Generated by Django 5.1.3 on 2024-11-30 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0006_alter_tour_available_places_alter_tour_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name_plural': 'Tours'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_people',
            field=models.IntegerField(help_text='Максимальное количество мест'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_people',
            field=models.IntegerField(help_text='Количество людей в группе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='web_site.tour'),
        ),
    ]
